---
name: nweb

releases:
- name: nweb-release
  version: latest

update:
  canaries: 1
  max_in_flight: 2
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

jobs:
- name: nweb
  vm_type: default
  azs:
  - z1
  stemcell: default
  templates:
  - name: nweb
  instances: 1
  networks:
  - name: default
    static_ips:
    - 10.10.0.10

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

properties: {}
#properties:
#  port: 8181

